from django.urls import path
from .views import *

urlpatterns = [
    path('', finances, name='finances'),
    #
    path('expenses/', expenses, name='expenses'),
    # driver expenses
    path('d_expenses/', d_expenses, name='d_expenses'),
    path('expenses/driver_exp/create', create_d_expense, name='create_d_expense'),
    path('expenses/driver_exp/<str:pk>/', d_expense, name='d_expense'),
    path('expenses/driver_exp/<str:pk>/audit',
         audit_d_expense, name='audit_d_expense'),
    path('expenses/driver_exp/<str:pk>/edit',
         edit_d_expense, name='edit_d_expense'),
    path('expenses/driver_exp/<str:pk>/delete',
         delete_d_expense, name='delete_d_expense'),
    path('d_expenses_csv/', d_expenses_csv, name='d_expenses_csv'),
    # vehicle expenses
    path('v_expenses/', v_expenses, name='v_expenses'),
    path('expenses/vehicle_exp/create',
         create_v_expense, name='create_v_expense'),
    path('expenses/vehicle_exp/<str:pk>/', v_expense, name='v_expense'),
    path('expenses/vehicle_exp/<str:pk>/audit',
         audit_v_expense, name='audit_v_expense'),
    path('expenses/vehicle_exp/<str:pk>/edit',
         edit_v_expense, name='edit_v_expense'),
    path('expenses/vehicle_exp/<str:pk>/delete',
         delete_v_expense, name='delete_v_expense'),
    path('v_expenses_csv/', v_expenses_csv, name='v_expenses_csv'),
    # global expenses
    path('g_expenses/', g_expenses, name='g_expenses'),
    path('expenses/global_exp/create', create_g_expense, name='create_g_expense'),
    path('expenses/global_exp/<str:pk>/', g_expense, name='g_expense'),
    path('expenses/global_exp/<str:pk>/audit',
         audit_g_expense, name='audit_g_expense'),
    path('expenses/global_exp/<str:pk>/edit',
         edit_g_expense, name='edit_g_expense'),
    path('expenses/global_exp/<str:pk>/delete',
         delete_g_expense, name='delete_g_expense'),
    path('g_expenses_csv/', g_expenses_csv, name='g_expenses_csv'),
    # transactions
    path('transactions/', transactions, name='transactions'),
    # payments
    path('payments/', payments, name='payments'),
    path('payments/create', create_payment, name='create_payment'),
    path('payments/<str:pk>/', payment, name='payment'),
    path('payments/<str:pk>/audit', audit_payment, name='audit_payment'),
    path('payments/<str:pk>/edit', edit_payment, name='edit_payment'),
    path('payments/<str:pk>/delete', delete_payment, name='delete_payment'),
    path('payments_csv/', payments_csv, name='payments_csv'),
    # payouts
    path('payouts/', payouts, name='payouts'),
    path('payouts/create', create_payout, name='create_payout'),
    path('payouts/<str:pk>/', payout, name='payout'),
    path('payouts/<str:pk>/audit', audit_payout, name='audit_payout'),
    path('payouts/<str:pk>/edit', edit_payout, name='edit_payout'),
    path('payouts/<str:pk>/delete', delete_payout, name='delete_payout'),
    path('payouts_csv/', payouts_csv, name='payouts_csv'),
    # revenues
    path('revenues/', revenues, name='revenues'),
    path('revenues/create', create_revenue, name='create_revenue'),
    path('revenues/<str:pk>/', revenue, name='revenue'),
    path('revenues/<str:pk>/edit', edit_revenue, name='edit_revenue'),
    path('revenues/<str:pk>/audit', audit_revenue, name='audit_revenue'),
    path('revenues/<str:pk>/delete', delete_revenue, name='delete_revenue'),
    path('revenues_csv/', revenues_csv, name='revenues_csv'),
    # ledgers
    path('ledgers/', ledgers, name='ledgers'),
    path('ledgers/create', create_ledger, name='create_ledger'),
    path('ledgers/<str:pk>/', ledger, name='ledger'),
    path('ledgers/<str:pk>/edit', edit_ledger, name='edit_ledger'),
    path('ledgers/<str:pk>/audit', audit_ledger, name='audit_ledger'),
    path('ledgers/<str:pk>/delete', delete_ledger, name='delete_ledger'),
    # vaults
    path('vaults/', vaults, name='vaults'),
    path('vaults/create', create_vault, name='create_vault'),
    path('vaults/<str:pk>/', vault, name='vault'),
    path('vaults/<str:pk>/edit', edit_vault, name='edit_vault'),
    path('vaults/<str:pk>/delete', delete_vault, name='delete_vault'),
    # balancesheet & audit
    path('balancesheet/', balancesheet, name='balancesheet'),
    path('audit/', audit, name='audit'),
    path('stats/', stats, name='stats'),
]
