# Generated by Django 4.2 on 2023-05-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
