# Generated by Django 4.1.7 on 2023-04-23 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_thread_first_person_thread_second_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread', to='chats.thread'),
        ),
    ]
