# Generated by Django 4.1.9 on 2023-06-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_chatmessage_receiver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
    ]
