# Generated by Django 4.2 on 2023-05-13 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='date_added',
            new_name='date_posted',
        ),
    ]
