# Generated by Django 4.1.9 on 2023-12-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.vehicle'),
        ),
        migrations.AddField(
            model_name='incident',
            name='vehicle',
            field=models.ForeignKey(default='007tog', on_delete=django.db.models.deletion.CASCADE, to='base.vehicle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='vehicle',
            field=models.ForeignKey(default='007tog', on_delete=django.db.models.deletion.CASCADE, to='base.vehicle'),
            preserve_default=False,
        ),
    ]
