# Generated by Django 4.1.13 on 2024-04-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_notification_chatnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatNotification',
        ),
    ]
