# Generated by Django 4.1.9 on 2023-06-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_document_documenttype_driver_incident_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='is_married',
        ),
        migrations.AddField(
            model_name='driver',
            name='martital_status',
            field=models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)'), ('Voeuf(ve)', 'Voeuf(ve)')], default='', max_length=50),
        ),
    ]
