# Generated by Django 4.1.9 on 2023-06-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_driverdocument_user_alter_vehicle_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='management',
            field=models.CharField(choices=[('Propriété personnelle', 'Propriété personnelle'), ('Mandat de gestion', 'Mandat de gestion')], default='', max_length=50),
        ),
    ]
