# Generated by Django 4.1.9 on 2023-06-13 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_vehicle_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdocument',
            name='user',
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.driver'),
        ),
        migrations.AddField(
            model_name='incident',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.driver'),
        ),
        migrations.AddField(
            model_name='incident',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.driver'),
        ),
    ]
