# Generated by Django 4.1.9 on 2023-06-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_driverdocument_user_driverdocument_driver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverdocument',
            old_name='posted_at',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='posted_at',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='vehicledocument',
            old_name='posted_at',
            new_name='date_posted',
        ),
    ]
