# Generated by Django 4.1.9 on 2023-06-13 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_posted_at_driverdocument_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.vehicle'),
        ),
    ]
