# Generated by Django 4.1.9 on 2023-06-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_driver_is_active_vehicle_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_solved',
            field=models.BooleanField(default='False'),
        ),
    ]
