# Generated by Django 4.1.9 on 2023-06-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_incident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledocument',
            name='vehicle',
        ),
    ]
