# Generated by Django 4.1.9 on 2023-06-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cost',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_count',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drivers',
            field=models.ManyToManyField(blank=True, to='base.driver'),
        ),
    ]
