# Generated by Django 4.1.9 on 2023-06-28 09:32

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_driver_is_active_alter_driverdocument_is_valid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='drivers',
        ),
        migrations.AddField(
            model_name='driver',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='place',
            field=models.CharField(default='nowhere', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='repairability',
            field=models.CharField(blank=True, choices=[('repairable', 'Reparable'), ('unrepairable', 'Irreparable')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='first_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_driver', to='base.driver'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='second_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_driver', to='base.driver'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='third_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_driver', to='base.driver'),
        ),
        migrations.CreateModel(
            name='PartnerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(blank=True)),
                ('expiry_date', models.DateTimeField(blank=True)),
                ('issuing_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='partner_docs')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.partner')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.documenttype')),
            ],
        ),
    ]
