# Generated by Django 4.1.9 on 2023-06-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_vehicle_drivers_driver_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
