# Generated by Django 4.1.9 on 2023-07-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_driver_first_name_alter_driver_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='mobility',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('immobile', 'Immobile')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='place_of_birth',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
