# Generated by Django 4.1.9 on 2023-07-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_incident_mobility_alter_driver_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, default='100')),
                ('observation', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='mobility',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobilisé'), ('immobile', 'Immobilisé')], default='', max_length=50, null=True),
        ),
    ]
