# Generated by Django 4.1.9 on 2023-07-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_rating_partner_is_active_alter_incident_mobility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_docs/'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='partners/'),
        ),
        migrations.AlterField(
            model_name='partnerdocument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='partner_docs/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_docs/'),
        ),
    ]
