# Generated by Django 4.1.9 on 2023-07-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_driverdocument_image_alter_incident_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='driver',
            name='observation',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='score',
            field=models.IntegerField(blank=True, default='100'),
        ),
    ]
