# Generated by Django 4.1.9 on 2023-07-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_company_banner_alter_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='contract',
        ),
        migrations.AddField(
            model_name='partner',
            name='commission',
            field=models.IntegerField(blank=True, default='100'),
        ),
    ]
