# Generated by Django 4.1.9 on 2023-07-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_remove_partner_contract_partner_commission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.AlterField(
            model_name='partner',
            name='commission',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
