# Generated by Django 4.1.9 on 2023-07-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_delete_contract_alter_partner_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
