# Generated by Django 4.1.9 on 2023-07-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_incident_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='severity',
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.incidenttype'),
        ),
    ]
