# Generated by Django 4.1.9 on 2023-07-28 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_tip_chatnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatnotification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
