# Generated by Django 4.1.9 on 2023-07-28 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0040_chatnotification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tip',
            name='article',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
