# Generated by Django 4.1 on 2023-08-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_tip_author_alter_tip_article_alter_tip_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='commission',
            field=models.IntegerField(blank=True, default='10'),
        ),
    ]
