# Generated by Django 4.1 on 2023-08-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_vehicle_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_count',
        ),
    ]
