# Generated by Django 4.1 on 2023-08-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_alter_vehicle_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
