# Generated by Django 4.1 on 2023-08-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_vehicle_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverdocument',
            old_name='date_posted',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='date_posted',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='partnerdocument',
            old_name='date_posted',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='tip',
            old_name='date_posted',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='vehicledocument',
            old_name='date_posted',
            new_name='date_added',
        ),
    ]
