# Generated by Django 4.1 on 2023-08-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_rename_date_posted_driverdocument_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='commission',
            field=models.IntegerField(default='10'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='state',
            field=models.CharField(choices=[('Neuf', 'Neuf'), ('Usagé\xa0', 'Usagé\xa0')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Manuelle', 'Manuelle'), ('Automatique', 'Automatique')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(),
        ),
    ]
