# Generated by Django 4.1.9 on 2023-12-19 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cash', 'Physique'), ('mobile', 'Mobile'), ('bank', 'Bancaire')], max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('acc_number', models.CharField(blank=True, max_length=255)),
                ('operator', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255, unique=True)),
                ('debit', models.IntegerField(blank=True, default='0')),
                ('credit', models.IntegerField(blank=True, default='0')),
                ('balance', models.IntegerField(blank=True, default='0')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('details', models.CharField(blank=True, max_length=1000, null=True)),
                ('amount', models.IntegerField(blank=True, default='0')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('is_audited', models.BooleanField(default=False)),
                ('receit', models.ImageField(blank=True, null=True, upload_to='vehicle_expenses')),
                ('vault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.vault')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_worked', models.IntegerField(default='0')),
                ('gross_income', models.IntegerField(blank=True, default='0')),
                ('net_income', models.IntegerField(blank=True, default='0')),
                ('comment', models.TextField(blank=True)),
                ('payday', models.DateTimeField(auto_now=True)),
                ('month', month.models.MonthField(blank=True, null=True, verbose_name='Mois')),
                ('is_audited', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.partner')),
                ('vault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.vault')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_worked', models.IntegerField(default='0')),
                ('amount', models.IntegerField(blank=True, default='0')),
                ('type', models.CharField(choices=[('salary', 'Salaire'), ('sabbatic', 'Paiement autonome sabbatique')], default='salary', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('payday', models.DateTimeField(auto_now=True)),
                ('is_audited', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.driver')),
                ('vault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.vault')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default='0')),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('payday', models.DateTimeField(auto_now=True)),
                ('is_audited', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.driver')),
                ('vault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.vault')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=1000, null=True)),
                ('debit', models.IntegerField(blank=True, default='0')),
                ('credit', models.IntegerField(blank=True, default='0')),
                ('date', models.DateField(blank=True, null=True)),
                ('is_audited', models.BooleanField(default=False)),
                ('vault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.vault')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('details', models.CharField(blank=True, max_length=1000, null=True)),
                ('amount', models.IntegerField(blank=True, default='0')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('is_audited', models.BooleanField(default=False)),
                ('receit', models.ImageField(blank=True, null=True, upload_to='global_expenses')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.vault')),
            ],
        ),
        migrations.CreateModel(
            name='DriverExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('details', models.CharField(blank=True, max_length=1000, null=True)),
                ('amount', models.IntegerField(blank=True, default='0')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('is_audited', models.BooleanField(default=False)),
                ('receit', models.ImageField(blank=True, null=True, upload_to='driver_expenses')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.driver')),
                ('vault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.vault')),
            ],
        ),
    ]
