# Generated by Django 4.1.9 on 2023-06-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleexpense',
            name='vehicle',
        ),
    ]
