# Generated by Django 4.1.9 on 2023-06-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_incident'),
        ('finances', '0002_remove_vehicleexpense_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleexpense',
            name='vehicle',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='base.vehicle'),
        ),
    ]
