# Generated by Django 4.1.9 on 2023-06-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_vehicleexpense_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverpayment',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='driverpayment',
            name='days_worked',
        ),
        migrations.RemoveField(
            model_name='driverpayment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='driverpayment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverpayment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
