# Generated by Django 4.1.9 on 2023-06-21 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0019_partner'),
        ('finances', '0004_rename_end_date_driverpayment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_count', models.IntegerField(default='0')),
                ('expenses', models.IntegerField(blank=True, default='0')),
                ('revenue', models.IntegerField(blank=True, default='0')),
                ('profit', models.IntegerField(blank=True, default='0')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DriverPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_worked', models.IntegerField(default='0')),
                ('amount', models.IntegerField(blank=True, default='0')),
                ('type', models.CharField(choices=[('salary', 'Salaire'), ('sabbatic', 'Paiement autonome sabbatique')], default='salary', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_paid', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
