# Generated by Django 4.1.9 on 2023-06-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_vehicle_driver_vehicle_cost_and_more'),
        ('finances', '0007_remove_investmentrecap_driver_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestmentRecap',
            new_name='Ledger',
        ),
    ]
