# Generated by Django 4.1.9 on 2023-06-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_rename_investmentrecap_ledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='title',
        ),
    ]
