# Generated by Django 4.1.9 on 2023-06-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_rename_end_date_ledger_date_remove_ledger_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='is_audited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_audited',
            field=models.BooleanField(default=False),
        ),
    ]
