# Generated by Django 4.1.9 on 2023-06-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_alter_ledger_is_audited_alter_payment_is_audited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='revenue',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='expenses',
            new_name='debit',
        ),
    ]
