# Generated by Django 4.1.9 on 2023-06-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_rename_motive_driverexpense_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverexpense',
            name='is_audited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalexpense',
            name='is_audited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payout',
            name='is_audited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleexpense',
            name='is_audited',
            field=models.BooleanField(default=False),
        ),
    ]
