# Generated by Django 4.1.9 on 2023-06-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_vehicle_is_active'),
        ('finances', '0014_driverexpense_is_audited_globalexpense_is_audited_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_worked', models.IntegerField(default='0')),
                ('commission', models.IntegerField(blank=True, default='0')),
                ('amount', models.IntegerField(blank=True, default='0')),
                ('details', models.TextField(blank=True)),
                ('date_paid', models.DateTimeField(auto_now=True)),
                ('is_audited', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.partner')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.vehicle')),
            ],
        ),
    ]
