# Generated by Django 4.1.9 on 2023-06-30 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_vehicle_is_active'),
        ('finances', '0015_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('commission', models.IntegerField(blank=True, default='0')),
                ('terms', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='revenue',
            old_name='details',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='revenue',
            old_name='amount',
            new_name='gross_income',
        ),
        migrations.RenameField(
            model_name='revenue',
            old_name='commission',
            new_name='net_income',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='partner',
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_worked', models.IntegerField(default='0')),
                ('gross_income', models.IntegerField(blank=True, default='0')),
                ('net_income', models.IntegerField(blank=True, default='0')),
                ('comment', models.TextField(blank=True)),
                ('date_paid', models.DateTimeField(auto_now=True)),
                ('is_audited', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.partner')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.vehicle')),
            ],
        ),
    ]
