# Generated by Django 4.1.9 on 2023-06-30 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_contract_alter_vehicle_plate_number_partner_contract'),
        ('finances', '0016_contract_rename_details_revenue_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.AlterField(
            model_name='vehicleexpense',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.vehicle'),
        ),
    ]
