# Generated by Django 4.1.9 on 2023-07-03 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_driver_first_name_alter_driver_last_name'),
        ('finances', '0019_alter_driverexpense_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.driver'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.driver'),
        ),
    ]
