# Generated by Django 4.1.9 on 2023-07-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0020_alter_payment_driver_alter_payout_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='driver',
        ),
    ]
