# Generated by Django 4.1.9 on 2023-07-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0023_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
    ]
