# Generated by Django 4.1.9 on 2023-07-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0024_remove_ledger_vehicle_delete_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('debit', models.IntegerField(blank=True, default='0')),
                ('credit', models.IntegerField(blank=True, default='0')),
                ('balance', models.IntegerField(blank=True, default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Cashdesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('debit', models.IntegerField(blank=True, default='0')),
                ('credit', models.IntegerField(blank=True, default='0')),
                ('balance', models.IntegerField(blank=True, default='0')),
            ],
        ),
    ]
