# Generated by Django 4.1.9 on 2023-07-22 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_remove_incident_severity_alter_incident_type'),
        ('finances', '0025_bank_cashdesk'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='acc_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='revenue',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.partner'),
        ),
        migrations.DeleteModel(
            name='Dividend',
        ),
    ]
