# Generated by Django 4.1.9 on 2023-07-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0027_ledger_mobilevault_rename_bank_bankvault_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cash', 'Physique'), ('mobile', 'Mobile'), ('bank', 'Bancaire')], max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('acc_number', models.CharField(blank=True, max_length=255)),
                ('operator', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255, unique=True)),
                ('debit', models.IntegerField(blank=True, default='0')),
                ('credit', models.IntegerField(blank=True, default='0')),
                ('balance', models.IntegerField(blank=True, default='0')),
            ],
        ),
        migrations.DeleteModel(
            name='BankVault',
        ),
        migrations.DeleteModel(
            name='CashVault',
        ),
        migrations.DeleteModel(
            name='MobileVault',
        ),
    ]
