# Generated by Django 4.1.9 on 2023-07-22 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0028_vault_delete_bankvault_delete_cashvault_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverexpense',
            name='vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.vault'),
        ),
        migrations.AddField(
            model_name='globalexpense',
            name='vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.vault'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.vault'),
        ),
        migrations.AddField(
            model_name='payment',
            name='vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.vault'),
        ),
        migrations.AddField(
            model_name='payout',
            name='vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.vault'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.vault'),
        ),
        migrations.AddField(
            model_name='vehicleexpense',
            name='vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.vault'),
        ),
    ]
