# Generated by Django 4.1.9 on 2023-07-31 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_tip_author_alter_tip_article_alter_tip_subtitle'),
        ('finances', '0029_driverexpense_vault_globalexpense_vault_ledger_vault_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Revenue',
            new_name='Profit',
        ),
    ]
