# Generated by Django 4.1.9 on 2023-07-31 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_tip_author_alter_tip_article_alter_tip_subtitle'),
        ('finances', '0030_rename_revenue_profit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profit',
            new_name='Revenue',
        ),
    ]
