# Generated by Django 4.1 on 2023-08-09 17:15

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0031_rename_profit_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='month',
            field=month.models.MonthField(blank=True, null=True, verbose_name='Mois'),
        ),
    ]
